In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("waste_dataset.csv")
df.head()

,waste,items_required,product_type,products_made,difficulty,usefulness_score
0,old_jeans+zipper,scissors+thread+needle,fashion,tote_bag+pencil_case+makeup_pouch,medium,9
1,glass_jar+pump_top,glue+paint,utility,soap_dispenser+lotion_bottle,easy,8
2,egg_carton+soil,water+seeds,gardening,seed_starter_pots+microgreens_tray,easy,9
3,cardboard_box+lens,glue+knife+tape,gadget,smartphone_projector+magnifier,medium,7
4,plastic_bottle+zipper,hot_glue+scissors,storage,apple_box+coin_purse,easy,6

In [4]:
df.columns

Index(['waste', 'items_required', 'product_type', 'products_made',
       'difficulty', 'usefulness_score'],
      dtype='object')

In [5]:
df = df[["waste", "product_type"]]
df.head()

                   waste product_type
0       old_jeans+zipper      fashion
1     glass_jar+pump_top      utility
2        egg_carton+soil    gardening
3     cardboard_box+lens       gadget
4  plastic_bottle+zipper      storage

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["product_type"] = le.fit_transform(df["product_type"])

df.head()

                   waste  product_type
0       old_jeans+zipper             5
1     glass_jar+pump_top            15
2        egg_carton+soil             8
3     cardboard_box+lens             7
4  plastic_bottle+zipper            13

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df["waste"])

y = df["product_type"]

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier()

model.fit(X_train, y_train)

print("Model trained")

Model trained

In [9]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7297297297297297

In [10]:
def predict_product_type(text):
    text_vec = vectorizer.transform([text])
    pred = model.predict(text_vec)
    label = le.inverse_transform(pred)
    return label[0]

In [11]:
predict_product_type("plastic_bottle wire")

'storage'

In [14]:
predict_product_type("cardboard paper")

'decoration'

In [16]:
predict_product_type("old_jeans cloth")

'storage'

In [18]:
import joblib
!pip install joblib
joblib.dump(model, "model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")
joblib.dump(le, "label_encoder.pkl")

Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)

['label_encoder.pkl']

In [19]:
!ls

label_encoder.pkl  model.pkl  sample_data  vectorizer.pkl  waste_dataset.csv

In [20]:
from google.colab import files

files.download("model.pkl")
files.download("vectorizer.pkl")
files.download("label_encoder.pkl")